/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Odev3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test 
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test 
    public void testFound(){
        //Girilen Eleman arrayde mevcut. Bu fonksiyondan true dönmeli
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertTrue(App.search(array, 4));
    }

    @Test 
    public void testNotFound(){
        //Girilen Eleman arrayde mevcut. Bu fonksiyondan false dönmeli
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
        assertFalse(App.search(array, 5));
    }

    @Test void testEmptyArray(){
        //Array boş, aranan her eleman sonunda false dönmeli
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.search(array, 1));
    }

    @Test void testNull(){
        assertFalse(App.search(null, 1));
        
    }
}
